Arm64 support
YunoHost-Apps/overleaf_ynh pull request #10
Opened 2022-08-19 11:47 UTC by MohamedElashri

## Problem

- *Description of why you made this PR*

The application doesn't install on arm machines and doesn't clean up correctly

## Solution
. Add a way to build and install the app on arm machines.

- *And how do you fix that problem*
Changed the value for MongoDB repo to a one to support both `arm64` and `amd64`

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2023-09-12 20:41 UTC, yalh76 requested changes

2023-09-12 20:41 UTC, yalh76 commented on scripts/ynh_mongo_db
> +MONGO_CE_REPO="deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse"
YunoHost is debian based, not ubuntu based ..

2023-09-13 17:27 UTC, yalh76 commented
!testme

2024-06-05 06:49 UTC, Thovi98 commented
Since Yunohost 11.2.13 mongo helper is integrated into the core so we cannot change this on app basis anymore.

2024-06-05 06:49 UTC, closed without merging